### ISSUE TITLE
Support for associations and neighbors?

### ISSUE THREAD

**Issue by ghost** [jimjibone/goopenzwave#21]
Hi, I noticed some code related to associations that was commented out.
Do you plan to add support for associations and neighbors?

Thanks

**Comment by jimjibone** [comment]
Hi @hspaaij, sorry for the massively delayed reply.

I would like associations and neighbours to be supported, but so far I have had no need for them and so have not implemented them! I'm a little tight for time at the moment so I would welcome someone implementing it for me 😄

**Comment by hspaaij** [comment]
Hi @jimjibone, no worries, as you can see I'm no better :smile: 
I'll see what I can do.

<sidetrack1>However, first I'd like to try to link goopenzwave against a standard OZW installation. Hopefully that makes a Raspberry Pi installation easier. Once I've figured that out I'll create a ticket and a PR. I'm new to Go but have quite a bit of history with C/C++, so hopefully something useful will come out of it. Once that works I'll look at associations.
Stay tuned :)
</sidetrack1>
<sidetrack2>
btw, I'm using goopenzwave to make a homie/mqtt binding for openzwave. If you're interested I'll share it once it reaches usable levels
</sidetrack2>

**Comment by jimjibone** [comment]
Hi @hspaaij, changing goopenzwave to use a standard OZW installation is something I would like, actually. I might implement this myself and will open a new issue for it. Unless you're already working on it?

I didn't know of homie but it looks interesting! Yes, I'd be interested to see your binding when you're ready to share it. I'm actually working on my own home automation system at the moment which I hope to release soon.
