### ISSUE TITLE
Use system OZW installation

### ISSUE THREAD

**Issue by jimjibone** [jimjibone/goopenzwave#22]
As suggested in #21, switch to a system installation of OZW.

Original reason to bundle OZW as a submodule was to use a fixed version with goopenzwave, however this is not necessary as recent releases of OZW have shown to be backwards compatible.

Using an up-to-date system installation of OZW would be preferable as this library will benefit from the improvements and it can share configuration, etc. with other OZW based software such as the open-zwave-control-panel.

**Comment by hspaaij** [comment]
Hi, I tried using the standard OZW installation and had success by changing goopenzwave_linux.go as follows:
`package goopenzwave

// #cgo LDFLAGS: -lopenzwave
// #cgo CFLAGS:   -I/usr/include/openzwave -I/usr/local/include
// #cgo CPPFLAGS: -I/usr/include/openzwave -I/usr/local/include
import "C"
`
Some notes:
- This ran fine on both Ubuntu and on Raspberry Pi. 
- I looked into using pkgconfig but openzwave doesn't ship with a .pc file
- Didn't put a PR in as I'm not familiar with the environment and it might too narrow of an approach.

**Comment by jimjibone** [comment]
Thanks for the info! No problem about not doing a PR. I'll take a look at this and make it at least compatible with linux and macos. Things get more complicated with Windows... and actually might be easier by keeping the submodule.

What version of OpenZwave were you using by the way? Installation via the package manager or manual installation from source?

**Comment by jimjibone** [comment]
Here's my initial version using pkg-config, tested on macos: https://github.com/jimjibone/goopenzwave/tree/22-use-system-ozw-installation

**Comment by hspaaij** [comment]
For both Ubuntu and Raspbian the package manager version was used.  For both Raspbian and Ubuntu: (apt search openzwave)
libopenzwave1.5/bionic,now 1.5+ds-5 amd64 [installed,automatic]
  API to use a Z-Wave controller

libopenzwave1.5-dev/bionic,now 1.5+ds-5 amd64 [installed]
  header files for the openzwave library

**Comment by jimjibone** [comment]
Ahh right ok. Shame that the packages don't contain pkg-config files...

I'll try out the package manager version with my Pi.

Unfortunately homebrew on macos ships an old version of the library -- looks like it's mostly due to people running into the same build issues that we've seen before, asking open-zwave for the fix, not getting any response and then the PRs being closed after a load of hard work...

I'd like to switch to the package manager version completely.

**Comment by jimjibone** [comment]
Ok, just tested out the apt version of openzwave on Raspbian Jessie (v1.5) and it looks like it has installed a fairly old version of the device XML files! Some of my devices have not been correctly recognised annoyingly.

So I think for now I'm going to have to recommend an installation from source, unfortunately. At least that way you get an up-to-date device database, pkg-config files and latest set of features. Hopefully that doesn't include the latest set of bugs too...
